name: Build and test workflow
description: 'Affiche Hello world avec une chaîne de caractères personnalisée'

inputs:
  author:
    type: string
    required: false
    default: 'Steve'

runs:
  using: 'composite'
  steps:
    - name: "Greeting"
      run: echo "Hello World, ${{ inputs.author }} !"
      shell: bash